import type { LapArchetype, LapTraitKey } from './types';

/**
 * Archetype Target Matrix (Developer Formula Sheet v1).
 * Weights: 3 = core driver … −2 = strong tension
 */
export const LAP_ARCHETYPE_WEIGHT_MATRIX: Record<LapArchetype, Record<LapTraitKey, number>> = {
  Commander: {
    extroverted: 3,
    introverted: -2,
    decisive: 3,
    reflective: -1,
    confident: 2,
    humble: -1,
    directive: 3,
    collaborative: -2,
    certain: 2,
    curious: -1,
  },
  Trailblazer: {
    extroverted: 3,
    introverted: -1,
    decisive: 3,
    reflective: -1,
    confident: 2,
    humble: 0,
    directive: 1,
    collaborative: 1,
    certain: -1,
    curious: 3,
  },
  'Standard-Bearer': {
    extroverted: 2,
    introverted: -1,
    decisive: 1,
    reflective: 1,
    confident: 3,
    humble: -2,
    directive: 3,
    collaborative: -1,
    certain: 3,
    curious: -2,
  },
  Catalyst: {
    extroverted: 3,
    introverted: -1,
    decisive: 1,
    reflective: 1,
    confident: 1,
    humble: 1,
    directive: -1,
    collaborative: 3,
    certain: -1,
    curious: 3,
  },
  Strategist: {
    extroverted: -1,
    introverted: 3,
    decisive: -1,
    reflective: 3,
    confident: 2,
    humble: 0,
    directive: 1,
    collaborative: 1,
    certain: 0,
    curious: 3,
  },
  Integrator: {
    extroverted: 0,
    introverted: 1,
    decisive: -1,
    reflective: 3,
    confident: 0,
    humble: 2,
    directive: -2,
    collaborative: 3,
    certain: 1,
    curious: 1,
  },
  Anchor: {
    extroverted: -1,
    introverted: 2,
    decisive: 1,
    reflective: 1,
    confident: -1,
    humble: 3,
    directive: -1,
    collaborative: 3,
    certain: 3,
    curious: -1,
  },
  Guide: {
    extroverted: -1,
    introverted: 2,
    decisive: -2,
    reflective: 3,
    confident: -1,
    humble: 3,
    directive: -2,
    collaborative: 3,
    certain: -1,
    curious: 2,
  },
};
